---
- name: Install network configuration
  copy:
    dest: '/etc/systemd/network/ens18.network'
    src: ens18.network
    owner: root
    group: root
    mode: 0644
  tags:
  - networkd

# vim: set ts=2 sw=2 et:
